# network_scanner_alerts.yaml
# version: 0.14.2 (2025-11-14)

blueprint:
  name: Network Scanner – Alerts (Lean)
  description: >
    v0.14.2 — Alerts on new devices and high-risk devices from the
    Network Scanner Extended (Lean) sensor. Lets you ignore MACs and
    plug in your own notification action(s).
  domain: automation
  source_url: https://raw.githubusercontent.com/paganl/network_scanner_extended/refs/heads/main/blueprints/network_scanner_guardrail.yaml
  
  homeassistant:
    min_version: 2024.10.0

  input:
    network_sensor:
      name: Network Scanner sensor
      description: Sensor with attributes 'flat' and 'last_refresh_utc'
      selector: { entity: { domain: sensor } }

    high_risk_threshold:
      name: High-risk threshold
      default: 60
      selector: { number: { min: 0, max: 100, step: 5, mode: slider } }

    ignore_macs:
      name: Ignore MACs
      description: List of MACs to ignore (any case/format is fine)
      default: []
      selector: { object: {} }

    notify_actions:
      name: Notification actions
      description: >
        Action sequence that sends a message; you may reference
        {{ ns_title }} and {{ ns_message }} here.
      selector: { action: {} }

    blueprint_version:
      name: Blueprint version (do not change)
      default: "0.5.1"
      selector: { text: {} }

# Trigger when the coordinator stamps a new refresh time
trigger:
  - platform: template
    value_template: "{{ state_attr(i_sensor, 'last_refresh_utc') }}"

# Bind inputs to variables (never use !input inside {{ ... }})
variables:
  i_sensor: !input network_sensor
  i_ignore: !input ignore_macs
  i_threshold: !input high_risk_threshold
  i_version: !input blueprint_version

  # Normalise ignore MACs to uppercase once
  _ignore: >
    {{ (i_ignore or []) | map('string') | map('upper') | list }}

  # Pull and filter the 'flat' view from the sensor
  flat: >
    {{ (state_attr(i_sensor, 'flat') or [])
       | rejectattr('mac','in', _ignore)
       | list }}

  # Precompute sets we’ll test in conditions
  new_list: >
    {{ flat | selectattr('new','eq', true) | list }}
  high_risk_list: >
    {{ flat | selectattr('risk','ge', i_threshold) | list }}

  # Safe defaults to avoid “undefined” warnings
  ns_title: ""
  ns_message: ""

condition: []

action:
  - choose:
      # Branch A — New devices present
      - conditions:
          - condition: template
            value_template: "{{ new_list | length > 0 }}"
        sequence:
          - variables:
              ns_title: "New devices detected ({{ new_list | length }}) — v{{ i_version }}"
              ns_message: >
                {% for d in new_list -%}
                • {{ d.hostname or d.mac }} · {{ d.ip or '—' }} · VLAN {{ d.vlan_id if d.vlan_id is not none else '—' }} · {{ d.vendor or 'Unknown' }}
                {% endfor %}
          - sequence: !input notify_actions

      # Branch B — High-risk devices present
      - conditions:
          - condition: template
            value_template: "{{ high_risk_list | length > 0 }}"
        sequence:
          - variables:
              ns_title: "High-risk devices ({{ high_risk_list | length }}) — v{{ i_version }}"
              ns_message: >
                {% for d in high_risk_list -%}
                • {{ d.hostname or d.mac }} · risk={{ d.risk }} · role={{ d.role or '—' }} · {{ d.ip or '—' }}
                {% endfor %}
          - sequence: !input notify_actions

mode: restart
